#!/usr/bin/env python

from typing import List, Dict, Any
import sys
import os
from pathlib import Path


def main(args: List[str], **factory_kwargs: Dict[str, Any]):
    entry_path = Path(args[0])
    src_path = entry_path.parent / 'src' / 'python'
    conf_path = entry_path.parent / 'test-resources' / 'bibstract.conf'
    if not conf_path.exists():
        conf_path = Path(os.environ['BIBSTRACTRC'])
    args = args + ['-c', str(conf_path)]
    sys.path.append(str(src_path))
    from zensols.bibstract import main
    main(args[1:], **factory_kwargs)


def proto():
    print('-->proto')
    try:
        args = 'bibstract -c test-resources/bibstract.conf export test-resources/someproj'.split()
        main(args, reload_factory=True)
    except SystemExit as e:
        print(f'exit: {e}')


if (__name__ == '__main__'):
    # when running from a shell, run the CLI entry point
    import __main__ as mmod
    if hasattr(mmod, '__file__'):
        main(sys.argv)
    # otherwise, assume a Python REPL and run the prototyping method
    else:
        proto()
