#!/usr/bin/env python

from zensols.cli import ConfigurationImporterCliHarness

harness = ConfigurationImporterCliHarness(
    src_dir_name='src/python',
    app_factory_class='zensols.bibstract.ApplicationFactory',
    proto_args='package test-resources/someproj:zenbuild/src/sty',
    proto_factory_kwargs={'reload_pattern': r'^zensols.bibstract'},
)
harness.run()
